### ISSUE TITLE
tox -e lint fails if pylintfileheader is not installed

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibmq-provider#828]
### Information

- **Qiskit IBMQ Provider version**: master (7b93f78)
- **Python version**: 3.7
- **Operating system**: `Linux osboxes 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### What is the current behavior?

Running `tox -e lint` fails with this:

```
$ tox -e lint
lint recreate: /home/osboxes/github-other/qiskit-ibmq-provider/.tox/lint
lint installdeps: pycodestyle, pylint, doc8, ipython
lint develop-inst: /home/osboxes/github-other/qiskit-ibmq-provider
lint installed: astroid==2.3.3,attrs==20.3.0,backcall==0.2.0,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,contextvars==2.4,cryptography==3.2.1,decorator==4.4.2,dill==0.3.3,doc8==0.8.1,docutils==0.16,fastjsonschema==2.14.5,idna==2.10,immutables==0.14,importlib-metadata==3.1.1,ipython==7.16.1,ipython-genutils==0.2.0,isort==4.3.21,jedi==0.17.2,jsonschema==3.2.0,lazy-object-proxy==1.4.3,mccabe==0.6.1,mpmath==1.1.0,nest-asyncio==1.4.3,networkx==2.5,ntlm-auth==1.5.0,numpy==1.19.4,parso==0.7.1,pbr==5.5.1,pexpect==4.8.0,pickleshare==0.7.5,ply==3.11,prompt-toolkit==3.0.8,psutil==5.7.3,ptyprocess==0.6.0,pycodestyle==2.6.0,pycparser==2.20,Pygments==2.7.3,pylint==2.4.4,pyrsistent==0.17.3,python-constraint==1.4.0,python-dateutil==2.8.1,-e git+git@github.com:Qiskit/qiskit-ibmq-provider.git@7b93f7835b092bfee3694bf67c164a6edb9bd1bd#egg=qiskit_ibmq_provider,qiskit-terra==0.16.1,requests==2.25.0,requests-ntlm==1.1.0,restructuredtext-lint==1.3.2,retworkx==0.7.1,scipy==1.5.4,six==1.15.0,stevedore==3.3.0,sympy==1.7,traitlets==4.3.3,typed-ast==1.4.1,urllib3==1.26.2,wcwidth==0.2.5,websockets==8.1,wrapt==1.11.2,zipp==3.4.0
lint run-test-pre: PYTHONHASHSEED='3581956728'
lint run-test: commands[0] | pycodestyle test
lint run-test: commands[1] | pylint -rn --rcfile=/home/osboxes/github-other/qiskit-ibmq-provider/.pylintrc test
Traceback (most recent call last):
  File "/home/osboxes/github-other/qiskit-ibmq-provider/.tox/lint/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/osboxes/github-other/qiskit-ibmq-provider/.tox/lint/lib/python3.6/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/osboxes/github-other/qiskit-ibmq-provider/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 1686, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/osboxes/github-other/qiskit-ibmq-provider/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 660, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/home/osboxes/github-other/qiskit-ibmq-provider/.tox/lint/lib/python3.6/site-packages/astroid/modutils.py", line 198, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "/home/osboxes/github-other/qiskit-ibmq-provider/.tox/lint/lib/python3.6/site-packages/astroid/modutils.py", line 240, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
  File "/usr/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'pylintfileheader'
```

### Steps to reproduce the problem

simple, see above (make sure you don't have `pylintfileheader` installed globally)

### What is the expected behavior?

tox environments should be self-contained and install what is needed to run the target environment.

### Suggested solutions

Add `pylintfileheader` to the `deps` section for the `lint` tox env.

**Comment by mtreinish** [comment]
We probably should fix this by just copying over the script I wrote to do this for terra: https://github.com/Qiskit/qiskit-terra/blob/master/tools/verify_headers.py the pylintfileheader plugin was problematic when we used it in terra. There were a lot of scenarios where it would just fail and give no indication as to the cause.

**Comment by mriedem** [comment]
#828 fixes my immediate local development issue along with some new pylint error that started showing up (not sure why, it seems to be causing all changes to fail their lint check now). I don't have an opinion on #831, I'll defer to @jyu00.

For now I'm avoiding tox locally and using the make commands with a virtual environment (which is what tox is for, but alas).
