### ISSUE TITLE
ibmq_qasm_simulator times out unexpectedly

### ISSUE THREAD

**Issue by DevelopDaily** [Qiskit/qiskit-ibmq-provider#913]
### Information

- **Qiskit IBMQ Provider version**: Currently hosted at https://quantum-computing.ibm.com/
- **Python version**: Currently hosted at https://quantum-computing.ibm.com/
- **Operating system**: Currently hosted at https://quantum-computing.ibm.com/

### What is the current behavior?
I can run a circuit on the IBM Quantum Lab with 1 shot successfully. It takes 20 minutes. But, when I run the same circuit with 2 shots, it will always time out. 

### Steps to reproduce the problem

Pick up any of your circuits that are big enough to last for 20 minutes for 1 shot. Then, increase it to 2 shots. Observe the timeout.

### What is the expected behavior?

I expect it would take 40 minutes to complete a 2-shot job since the same job takes only 20 minutes to complete 1 shot.

### Suggested solutions
The performance for the simulator should be linear with shots.

**Comment by jyu00** [comment]
Hi @DevelopDaily, can you please post the timeout error you observed? Thanks.

**Comment by DevelopDaily** [comment]
Actually, there are two errors. When I am "lucky", I get this error:

`5201  Job timed out after 10000 seconds.`

When I am totally unlucky, I get the error `5204`, which is not documented. So, the job does not even get a chance to run. When that happens, the python stack trace looks like this:

```
Traceback (most recent call last):
  File "<ipython-input-6-083d719d6d53>", line 17, in <module>
    counts = job.result().get_counts()
  File "/opt/conda/lib/python3.8/site-packages/qiskit/providers/ibmq/job/ibmqjob.py", line 285, in result
    error_message = self.error_message()
  File "/opt/conda/lib/python3.8/site-packages/qiskit/providers/ibmq/job/ibmqjob.py", line 525, in error_message
    self._retrieve_result()
  File "/opt/conda/lib/python3.8/site-packages/qiskit/providers/ibmq/job/ibmqjob.py", line 952, in _retrieve_result
    self._set_result(result_response)
  File "/opt/conda/lib/python3.8/site-packages/qiskit/providers/ibmq/job/ibmqjob.py", line 985, in _set_result
    raise IBMQJobApiError(
IBMQJobApiError: "Unable to retrieve result for job 606f7c68d89dd50461ecc7ca: 'results'"
```

**Comment by jyu00** [comment]
@DevelopDaily I've made some inquiry with IBM Quantum Lab support. It seems that the job `606f7c68d89dd50461ecc7ca` failed immediately rather than being timed out. Unfortunately they didn't have more details on why it failed.

If possible, can you run your job locally on the Aer simulator with shots=2? e.g.
```
from qiskit import Aer
backend = Aer.get_backend('qasm_simulator')
backend.run(qobj)
```

This would give us a better idea on whether the issue is related to your code (unlikely if you could run 1 shot) or the simulator.

**Comment by DevelopDaily** [comment]
I will try it, but I am afraid my machine is too small for the circuit.

Would you please run it if I upload the circuit here or share it on the IBM Quantum Lab?

**Comment by jyu00** [comment]
@DevelopDaily I don't have access to your Quantum Lab code, but if you post the circuit here I can try running it.

**Comment by DevelopDaily** [comment]
Here it goes. I can confirm it succeeded in 1 shot. This time, it took 45 minutes. It used to take 20 minutes. Anyway, it will fail with 2 shots.


[1_1147_184_11-1shot.zip](https://github.com/Qiskit/qiskit-ibmq-provider/files/6346550/1_1147_184_11-1shot.zip)
